[build]
  command = "npm run build"
  publish = "out_publish"
  functions = "out_functions"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force HTTPS
[[redirects]]
  from = "http://:hostName/:splat"
  to = "https://:hostName/:splat"
  status = 301
  force = true

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
