[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions/"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force HTTPS
[[redirects]]
  from = "http://*/:splat"
  to = "https://:splat"
  status = 301
  force = true

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
